# Build brand assets from the supplied Parity Lending logo.
# - removes the mouse-cursor artifact baked into the uploaded screenshot
# - converts the white background to transparency (un-premultiplied)
# - emits logo.png, logo-white.png, mark.png, favicon.png and base64 data URIs
from PIL import Image, ImageDraw
import base64, os

SRC = "/root/.claude/uploads/7807b22d-0381-567a-a925-069eb9790111/42e0f448-1785344771805_image.png"
CURSOR_BOX = (173, 0, 206, 20)   # x0,y0,x1,y1 in source pixels
os.makedirs("assets", exist_ok=True)

src = Image.open(SRC).convert("RGB")
ImageDraw.Draw(src).rectangle(CURSOR_BOX, fill=(255, 255, 255))

W, H = src.size
px = src.load()
out = Image.new("RGBA", (W, H))
op = out.load()
for y in range(H):
    for x in range(W):
        r, g, b = px[x, y]
        a = 255 - min(r, g, b)
        if a <= 3:
            op[x, y] = (0, 0, 0, 0)
        else:
            f = a / 255.0
            op[x, y] = (int(max(0, min(255, (r - (255 - a)) / f))),
                        int(max(0, min(255, (g - (255 - a)) / f))),
                        int(max(0, min(255, (b - (255 - a)) / f))), a)

out = out.crop(out.getbbox())
w, h = out.size
p = out.load()

# white-on-dark variant
white = Image.new("RGBA", (w, h))
wp = white.load()
for y in range(h):
    for x in range(w):
        r, g, b, a = p[x, y]
        if a == 0:
            wp[x, y] = (0, 0, 0, 0); continue
        sat = max(r, g, b) - min(r, g, b)
        if sat > 45 and b >= r:      wp[x, y] = (108, 140, 235, a)   # chevron blue
        elif sat > 45 and r > b:     wp[x, y] = (240, 96, 84, a)     # chevron red
        else:                        wp[x, y] = (255, 255, 255, a)   # wordmark

# chevron mark on its own
cols = []
for x in range(w):
    hit = False
    for y in range(h):
        r, g, b, a = p[x, y]
        if a < 120: continue
        if (b > 120 and b - r > 50) or (r > 140 and r - b > 60):
            hit = True; break
    cols.append(hit)
first = cols.index(True); last = first
for x in range(first, w):
    if cols[x]: last = x
    elif x - last > 12: break
mark = out.crop((max(0, first - 2), 0, last + 3, h))
mark = mark.crop(mark.getbbox())

fav = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
s = min(58 / mark.size[0], 58 / mark.size[1])
m2 = mark.resize((int(mark.size[0] * s), int(mark.size[1] * s)), Image.LANCZOS)
fav.paste(m2, ((64 - m2.size[0]) // 2, (64 - m2.size[1]) // 2), m2)


def save(img, path, maxw=None):
    if maxw and img.size[0] > maxw:
        img = img.resize((maxw, int(img.size[1] * maxw / img.size[0])), Image.LANCZOS)
    img.quantize(colors=64, method=Image.FASTOCTREE).convert("RGBA").save(path, optimize=True)
    return path


save(out, "assets/logo.png", 360)
save(white, "assets/logo-white.png", 360)
save(mark, "assets/mark.png")
save(fav, "assets/favicon.png")
out.save("assets/logo@2x.png"); white.save("assets/logo-white@2x.png")

b64 = lambda f: "data:image/png;base64," + base64.b64encode(open(f, "rb").read()).decode()
data = {"LOGO_DATA": b64("assets/logo.png"),
        "LOGO_WHITE_DATA": b64("assets/logo-white.png"),
        "MARK_DATA": b64("assets/mark.png"),
        "FAVICON_DATA": b64("assets/favicon.png")}
with open("assets_data.py", "w") as fh:
    fh.write("# Auto-generated by make_assets.py from the Parity Lending logo.\n")
    for k, v in data.items():
        fh.write(f'{k} = "{v}"\n')
print("logo", out.size, "mark", mark.size)
for k, v in data.items():
    print(f"  {k:18s} {len(v)/1024:5.1f} KB")
